export * from './handlers/general.js'
export * from './handlers/cardMethods.js'
export * from './handlers/newPerson.js'
export * from './handlers/checkIfRelativesConnectedWithoutPerson.js'
export * from '../src/AddRelativeTree/AddRelativeTree.AddRelative.js'